encoding: utf-8

# Site settings
title: Laboratório de Aplicações de Informática em Saúde
email:
description: Laboratório de Aplicações de Informática em Saúde

baseurl: "/sitelab" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://renan-vinicius.github.io" # the base hostname & protocol for your site

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: facebook
    url: https://www.facebook.com/lapisusp
  - title: twitter
    url: https://twitter.com/lapis_usp


phone: "(11) 3018 1040"

collections:
  researches:
    output: false
  projects:
    output: true
    permalink: /project/:name

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", ".idea"]

plugins: [jekyll-paginate, jekyll-feed]
