encoding: utf-8

# Site settings
title: Laboratório de Aplicações de Informática em Saúde
email: fatima.nunes@usp.br
description: Laboratório de Aplicações de Informática em Saúde
header-img: "img/code.jpg"

baseurl: "/sitelab" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://renan-vinicius.github.io" # the base hostname & protocol for your site

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: facebook
    url: https://www.facebook.com/lapisusp
  - title: twitter
    url: https://twitter.com/lapis_usp


phone: "(11) 3018 1040"

collections:
  members:
    output: True
    permalink: /member/:name
  researches:
    output: false
  projects:
    output: true
    permalink: /project/:name

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["node_modules","gulpfile.js","package.json","package.json.lock","README.md", ".idea"]

plugins: [jekyll-paginate, jekyll-feed, jekyll-redirect-from]
